name: social_butterfly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
# Firebase related dependencies : 
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
# for debugging purposes . I use it instead of [print].
  logger: ^2.3.0 #https://pub.dev/packages/logger
# state management related dependencies
  bloc: ^8.1.4 # https://pub.dev/packages/bloc
  flutter_bloc: ^8.1.6 # https://pub.dev/packages/flutter_bloc
  equatable: ^2.0.5 # https://pub.dev/packages/equatable
# dependency injection
  get_it: ^7.7.0 #https://pub.dev/packages/get_it

  flutter_launcher_icons: ^0.13.1 # https://pub.dev/packages/flutter_launcher_icons
  google_sign_in: ^6.2.1 # https://pub.dev/packages/google_sign_in
  gap: ^3.0.1 #https://pub.dev/packages/gap
  email_validator: ^3.0.0 #https://pub.dev/packages/email_validator

# For Animations
  rive: ^0.13.9 #https://pub.dev/packages/rive2
# I use this package to show skeleton for loading widget  
  skeletonizer: ^1.3.0 #https://pub.dev/packages/skeletonizer
# For taking a picture
  image_picker: ^1.1.2 #https://pub.dev/packages/image_picker
# I use [intl] package to format DateTime text.
  intl: ^0.19.0 #https://pub.dev/packages/intl

dev_dependencies:
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/AppIcon.png" 

flutter_native_splash:
  color: "#F4F4F9" # Background color of the splash screen
  image: "lib/core/assets/Splash Screen.png" # Path to your splash screen image
  android: true
  ios: true
  web: true
  android_gravity: center # Control how the splash image is aligned
  ios_content_mode: scaleAspectFill # Control how the splash image is aligned
  fullscreen: true # Makes splash screen fullscreen



flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/
    - lib/core/assets/icons/
    - lib/core/assets/images/
    - lib/core/assets/animations/
    