name: social_butterfly
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
# Firebase related dependencies : 
  firebase_core: ^3.1.1
# for debugging
  logger: ^2.3.0
# state management related dependencies
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
# dependency injection
  get_it: ^7.7.0

  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/AppIcon.png" 

flutter_native_splash:
  color: "#F4F4F9" # Background color of the splash screen
  image: "lib/core/assets/Splash Screen.png" # Path to your splash screen image
  android: true
  ios: true
  web: true
  android_gravity: center # Control how the splash image is aligned
  ios_content_mode: scaleAspectFill # Control how the splash image is aligned
  fullscreen: true # Makes splash screen fullscreen



flutter:


  uses-material-design: true

  assets:
    - lib/core/assets/
    



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
