// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4sLxBpKeKtrV_ew1TPjB3-2411W17QZE',
    appId: '1:724239220075:web:6537abd8c395ebb47c602e',
    messagingSenderId: '724239220075',
    projectId: 'social-butterfly-3c88f',
    authDomain: 'social-butterfly-3c88f.firebaseapp.com',
    storageBucket: 'social-butterfly-3c88f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3w5Ke9bvdFQSzjz9HHlKW1u-G2x9FEk8',
    appId: '1:724239220075:android:282a955311fb6fc77c602e',
    messagingSenderId: '724239220075',
    projectId: 'social-butterfly-3c88f',
    storageBucket: 'social-butterfly-3c88f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBZSrlXIUnAm-fXhK44Ku1ffdggiogxrk',
    appId: '1:724239220075:ios:0a9c89ebf654a03f7c602e',
    messagingSenderId: '724239220075',
    projectId: 'social-butterfly-3c88f',
    storageBucket: 'social-butterfly-3c88f.appspot.com',
    iosBundleId: 'com.example.socialButterfly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBZSrlXIUnAm-fXhK44Ku1ffdggiogxrk',
    appId: '1:724239220075:ios:0a9c89ebf654a03f7c602e',
    messagingSenderId: '724239220075',
    projectId: 'social-butterfly-3c88f',
    storageBucket: 'social-butterfly-3c88f.appspot.com',
    iosBundleId: 'com.example.socialButterfly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4sLxBpKeKtrV_ew1TPjB3-2411W17QZE',
    appId: '1:724239220075:web:e67753e2fb2bb7d77c602e',
    messagingSenderId: '724239220075',
    projectId: 'social-butterfly-3c88f',
    authDomain: 'social-butterfly-3c88f.firebaseapp.com',
    storageBucket: 'social-butterfly-3c88f.appspot.com',
  );
}
